<<<<<<< HEAD
# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 07:58
=======
 -*- coding: utf-8 -*-
>>>>>>> 9ee79a7bc7deda2e135c38374f4039aaa95ed96a
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('consumer', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.BooleanField(default=False)),
                ('onum', models.CharField(max_length=20)),
                ('odata', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo'),
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='tprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.CartInfo'),
        ),
    ]
